[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "glg"
version = "0.0.0"
authors = [
    { name = "Vishal Pankaj Chandratreya" },
]
description = "It's a surprise tool that will help us later"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "pygit2",
]


[tool.hatch.envs.default]
system-packages = true

[tool.ruff.lint.per-file-ignores]
"src/glg/glg.py" = ["T201"]
